// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7QUUH89tU6-CfkgOJz7bISb94n2jQHNE',
    appId: '1:187718743439:web:61696fb5d977474b82c7fa',
    messagingSenderId: '187718743439',
    projectId: 'smart-home-b7b3f',
    authDomain: 'smart-home-b7b3f.firebaseapp.com',
    storageBucket: 'smart-home-b7b3f.firebasestorage.app',
    measurementId: 'G-1N5FBWMZCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTH1o3fc4tr0UPmLA9dS117ZHMD8IeXUQ',
    appId: '1:187718743439:android:9c54af2767f44d8582c7fa',
    messagingSenderId: '187718743439',
    projectId: 'smart-home-b7b3f',
    storageBucket: 'smart-home-b7b3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4F0ijPDV8GkiyYscL_oSJKWWIYTXhc3A',
    appId: '1:187718743439:ios:374b165938a8ee6582c7fa',
    messagingSenderId: '187718743439',
    projectId: 'smart-home-b7b3f',
    storageBucket: 'smart-home-b7b3f.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4F0ijPDV8GkiyYscL_oSJKWWIYTXhc3A',
    appId: '1:187718743439:ios:374b165938a8ee6582c7fa',
    messagingSenderId: '187718743439',
    projectId: 'smart-home-b7b3f',
    storageBucket: 'smart-home-b7b3f.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7QUUH89tU6-CfkgOJz7bISb94n2jQHNE',
    appId: '1:187718743439:web:c45cbb2c22a4ab9f82c7fa',
    messagingSenderId: '187718743439',
    projectId: 'smart-home-b7b3f',
    authDomain: 'smart-home-b7b3f.firebaseapp.com',
    storageBucket: 'smart-home-b7b3f.firebasestorage.app',
    measurementId: 'G-E33KSFK3D8',
  );
}
